version: 2.1

orbs:
  android: circleci/android@2.2.0

jobs:
  Check-Build-Health:
    docker:
      - image: soaboz/android-jdk-17:0.0.1
    resource_class: small
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - run:
          name: Check build health
          command: |
            ./gradlew buildHealth
      - android/save-gradle-cache
      - android/save-build-cache

  Core-Lint:
    docker:
      - image: soaboz/android-jdk-17:0.0.1
    resource_class: small
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - run:
          name: Ktlint
          command: ./gradlew :core:ktlintCheck

  Core-Test:
    docker:
      - image: soaboz/android-jdk-17:0.0.1
    resource_class: small
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - android/run-tests:
          test-command: ./gradlew :core:test
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit

  Core-Build:
    docker:
      - image: soaboz/android-jdk-17:0.0.1
    resource_class: small
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - run:
          name: Assemble Core Library
          command: |
            ./gradlew :core:assembleRelease
            echo $SIGNING_SECRET | base64 -d > ~/secret.gpg
            ./gradlew :core:publishToMavenLocal

  Rx2-Lint:
    docker:
      - image: soaboz/android-jdk-17:0.0.1
    resource_class: small
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - run:
          name: Ktlint
          command: ./gradlew :rx2:ktlintCheck

  Rx2-Test:
    docker:
      - image: soaboz/android-jdk-17:0.0.1
    resource_class: small
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - android/run-tests:
          test-command: ./gradlew :rx2:test
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit

  Rx2-Build:
    docker:
      - image: soaboz/android-jdk-17:0.0.1
    resource_class: small
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - run:
          name: Assemble Rx2 Library
          command: |
            ./gradlew :rx2:assembleRelease
            echo $SIGNING_SECRET | base64 -d > ~/secret.gpg
            ./gradlew :rx2:publishToMavenLocal

  Rx3-Lint:
    docker:
      - image: soaboz/android-jdk-17:0.0.1
    resource_class: small
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - run:
          name: Ktlint
          command: ./gradlew :rx3:ktlintCheck

  Rx3-Test:
    docker:
      - image: soaboz/android-jdk-17:0.0.1
    resource_class: small
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - android/run-tests:
          test-command: ./gradlew :rx3:test
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit

  Rx3-Build:
    docker:
      - image: soaboz/android-jdk-17:0.0.1
    resource_class: small
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - run:
          name: Assemble Rx3 Library
          command: |
            ./gradlew :rx3:assembleRelease
            echo $SIGNING_SECRET | base64 -d > ~/secret.gpg
            ./gradlew :rx3:publishToMavenLocal

  Coroutines-Lint:
    docker:
      - image: soaboz/android-jdk-17:0.0.1
    resource_class: small
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - run:
          name: Ktlint
          command: ./gradlew :coroutines:ktlintCheck

  Coroutines-Test:
    docker:
      - image: soaboz/android-jdk-17:0.0.1
    resource_class: small
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - android/run-tests:
          test-command: ./gradlew :coroutines:test
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit

  Coroutines-Build:
    docker:
      - image: soaboz/android-jdk-17:0.0.1
    resource_class: small
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - run:
          name: Assemble Coroutines Library
          command: |
            ./gradlew :coroutines:assembleRelease
            echo $SIGNING_SECRET | base64 -d > ~/secret.gpg
            ./gradlew :coroutines:publishToMavenLocal

  Livedata-Lint:
    docker:
      - image: soaboz/android-jdk-17:0.0.1
    resource_class: small
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - run:
          name: Ktlint
          command: ./gradlew :livedata:ktlintCheck

  Livedata-Test:
    docker:
      - image: soaboz/android-jdk-17:0.0.1
    resource_class: small
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - android/run-tests:
          test-command: ./gradlew :livedata:test
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit

  Livedata-Build:
    docker:
      - image: soaboz/android-jdk-17:0.0.1
    resource_class: small
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - run:
          name: Assemble Livedata Library
          command: |
            ./gradlew :livedata:assembleRelease
            echo $SIGNING_SECRET | base64 -d > ~/secret.gpg
            ./gradlew :livedata:publishToMavenLocal

workflows:
  version: 2
  Test-And-Build:
    jobs:
      - Check-Build-Health
      - Core-Lint:
          requires:
            - Check-Build-Health
      - Core-Test:
          requires:
            - Core-Lint
      - Core-Build:
          requires:
            - Core-Test
      - Rx2-Lint:
          requires:
            - Check-Build-Health
      - Rx2-Test:
          requires:
            - Rx2-Lint
      - Rx2-Build:
          requires:
            - Rx2-Test
      - Rx3-Lint:
          requires:
            - Check-Build-Health
      - Rx3-Test:
          requires:
            - Rx3-Lint
      - Rx3-Build:
          requires:
            - Rx3-Test
      - Coroutines-Lint:
          requires:
            - Check-Build-Health
      - Coroutines-Test:
          requires:
            - Coroutines-Lint
      - Coroutines-Build:
          requires:
            - Coroutines-Test
      - Livedata-Lint:
          requires:
            - Check-Build-Health
      - Livedata-Test:
          requires:
            - Livedata-Lint
      - Livedata-Build:
          requires:
            - Livedata-Test
