version: 2.1

orbs:
  android: circleci/android@2.2.0

jobs:
  Check-Build-Health:
    docker:
      - image: soaboz/android-jdk-17:0.0.1
    resource_class: small
    steps:
      - android/restore-gradle-cache
      - android/restore-build-cache
      - run:
          name: Check build health
          command: |
            ./gradlew buildHealth
      - android/save-gradle-cache
      - android/save-build-cache
  Core-Test:
    docker:
      - image: soaboz/android-jdk-17:0.0.1
    resource_class: small
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - android/run-tests:
          test-command: ./gradlew :core:test
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit

  Core-Build:
    docker:
      - image: soaboz/android-jdk-17:0.0.1
    resource_class: small
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - run:
          name: Assemble Core Library
          command: |
            ./gradlew :core:assembleRelease
            echo $SIGNING_SECRET | base64 -d > ~/secret.gpg
            ./gradlew :core:publishToMavenLocal

  Rx2-Test:
    docker:
      - image: soaboz/android-jdk-17:0.0.1
    resource_class: small
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - android/run-tests:
          test-command: ./gradlew :rx2:test
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit

  Rx2-Build:
    docker:
      - image: soaboz/android-jdk-17:0.0.1
    resource_class: small
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - run:
          name: Assemble Rx2 Library
          command: |
            ./gradlew :rx2:assembleRelease
            echo $SIGNING_SECRET | base64 -d > ~/secret.gpg
            ./gradlew :rx2:publishToMavenLocal

workflows:
  version: 2
  Test-And-Build:
    jobs:
      - Check-Build-Health
      - Core-Test:
          requires:
            - Check-Build-Health
      - Core-Build:
          requires:
            - Core-Test
      - Rx2-Test:
          requires:
            - Check-Build-Health
      - Rx2-Build:
          requires:
            - Rx2-Test

